#!/usr/bin/env python3.11

from regex import findall
from subprocess import call, check_output
import json


def choose_class(battery_val):
    class_dict = {
        range(100, 101): "full",
        range(90, 100): "veryhigh",
        range(75, 90): "high",
        range(60, 75): "medhigh",
        range(50, 60): "med",
        range(25, 50): "low",
        range(0, 25): "verylow",
    }

    for key, val in class_dict.items():
        if battery_val in key:
            return val


keyb_device = "/org/freedesktop/UPower/devices/battery_hid_dco2co26offo82o65_battery"

battery_list = check_output(["upower", "--enumerate"]).decode()

if keyb_device in battery_list:
    battery_info = check_output(["upower", "-i", keyb_device]).decode().splitlines()
    battery_val = int(
        [val for val in battery_info if "percentage:" in val][0]
        .split()[1]
        .strip()
        .replace("%", "")
    )

    model_val = [val for val in battery_info if "model:" in val][0].split()[1:]
    model_val = "".join(model_val).split()

    class_val = choose_class(battery_val)

    result_dict = {
        "text": f"{battery_val}% ",
        "tooltip": f"{model_val} connected via bluetooth",
        "class": class_val,
    }

    result_json = json.dumps(result_dict)
    print(result_json)

else:
    result_dict = {
        # "text": f" <span color='#eb4d4b'>X</span>",
        "text": f"",
        "tooltip": f"DIERYA DK63 not connected",
        "class": "disconnected",
    }

    result_json = json.dumps(result_dict)
    print(result_json)
