#!/usr/bin/env python3.11

from subprocess import check_output
import json
from tkinter import OFF

COLOR_ALT = "%{F#7c7c7c}"
COLOR_END = "%{F-}"

proc_info = check_output(["sensors", "asus-isa-0000"]).decode("utf-8")
speed = int((proc_info.splitlines()[-2]).split(" ")[-2])


if speed == 0:
    speed = "OFF"
    class_val = "off"
elif 0 < speed < 2200:
    class_val = "med"
elif speed > 2200:
    class_val = "low"

if speed != "OFF":
    result_dict = {
        "text": f"{speed} RPM",
        "tooltip": proc_info.strip(),
        "class": class_val,
    }

else:
    result_dict = {"text": f"{speed}", "tooltip": proc_info.strip(), "class": class_val}

result_json = json.dumps(result_dict)

print(result_json)
