#!/usr/bin/env python3.11

from subprocess import check_output
import json

COLOR_ALT = "%{F#7c7c7c}"
COLOR_END = "%{F-}"


# inputs_str = check_output(["swaymsg", "-t"  "get_inputs"])


layout_call = check_output(["setxkbmap", "-query"])
layout_call_string = layout_call.decode()
layout_list = layout_call_string.split("\n")
caps_status = ""
for line in layout_list:
    if "layout" in line:
        print(
            json.dumps(
                {
                    "text": f"{line[-3:].upper()+caps_status} ",
                    "tooltip": layout_call_string.strip(),
                }
            )
        )
